server:
  port: 8084

spring:
  application:
    name: fire-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: fire-service
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
