server:
  port: 8086

spring:
  application:
    name: alert-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: alert-service
  sleuth:
    sampler:
      probability: 1.0
