server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: temperature_route
          predicates:
            - Path=/temperature/**
          filters:
            - StripPrefix=1
          uri: http://localhost:8081
        - id: occupancy_route
          predicates:
            - Path=/occupancy/**
          filters:
            - StripPrefix=1
          uri: http://localhost:8082
  zipkin:
    base-url: http://localhost:9411
    service:
      name: gateway-service
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0