server:
  port: 8083

spring:
  application:
    name: climate-control-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: climate-control-service
  sleuth:
    sampler:
      probability: 1.0
