server:
  port: 8081

spring:
  application:
    name: temperature-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: temperature-service
  sleuth:
    sampler:
      probability: 1.0
