server:
  port: 8087

spring:
  application:
    name: contact-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: contact-service
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
