server:
  port: 8088

spring:
  application:
    name: asset-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: asset-service
  sleuth:
    sampler:
      probability: 1.0
