server:
  port: 8082

spring:
  application:
    name: occupancy-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: occupancy-service
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

